### ISSUE TITLE
checkpoints for USPTO-full

### ISSUE THREAD

**Issue by zhengkaitu** [uta-smile/RetroXpert#12]
Do you plan to release the checkpoint(s) for USPTO-full? I'm trying to perform some benchmarking studies with them. Thanks!

**Comment by chaoyan1037** [comment]
The problem is that the setting for USPTO-full is different, and I hard code these settings. In other words, the source code for USPTO-50K should be adjusted slightly to be compatible with USPTO-full. There is no plan to release the uncleaned code for USPTO-full since the source code for USPTO-full is ugly. As a result, it is meanless to release the checkpoints for USPTO-full.

If you are interested in USPTO-full, you may adapt the current implementation and train the model. Or if you are not in a hurry, I can prepare a branch for the USPTO-full, but I may need months to finish it since I have some other deadlines now.

**Comment by zhengkaitu** [comment]
Thanks for the reply! Would you mind briefly commenting on the main adjustments for your USPTO-full code? If I adapt the current implementation and train on the full set directly, would I get performance close to the one reported in the paper? Or would the code break at some point?

**Comment by chaoyan1037** [comment]
The main adjustments are about feature dimension since the semi-templates for the USPTO-full are much larger. The training will be fine, and you should get a similar performance.

**Comment by zhengkaitu** [comment]
Thanks! Will try

**Comment by chaoyan1037** [comment]
We have an important update of our method. Please refer to the readme for more details.
